language: java
sudo: false
before_script:
  - curl -sSL --create-dirs -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
script:
  - sbt -Dcapsulecrm.url=https://coen.capsulecrm.com -Dcapsulecrm.token=$CAPSULECRM_TOKEN test
jdk:
  - oraclejdk8
env:
  global:
  - secure: "OPU4H7V2ps6/9JxtOWaKnZTCdjv28CSrry1/NExFMTaLbTHTCkmVa44CXR4Lq5HWhY+URUAtst3391kpl3fa1wvbE2FfzXij9AJpSWspiMozzzGO1W3+h6TsOlVGbVweGU8GJeDb6XBE7puVp5U3O1i8lbYVmAznfnRQ4uW7PLs="
cache:
  directories:
  - $HOME/.ivy2